// import 'package:sih2/models/busdetails.dart';
//
// List<busdetails> listofbus = [
//   busdetails(
//     id: "1",
//     name: "GSRTC",
//     type: "Express",
//     departingtime: "07:00 AM",
//     reachtime: "01:00 PM",
//     duration: "06:00",
//     stations: "ABD, BRD, BRC, SRT",
//     availableseats: 30,
//     ticketprice: 150,
//   ),
//   busdetails(
//     id: "2",
//     name: "GSRTC",
//     type: "Express",
//     departingtime: "09:00 AM",
//     reachtime: "03:00 PM",
//     duration: "06:00",
//     stations: "ABD, BRD, BRC, SRT",
//     availableseats: 25,
//     ticketprice: 175,
//   ),
//   busdetails(
//     id: "3",
//     name: "GSRTC",
//     type: "Express",
//     departingtime: "11:00 AM",
//     reachtime: "05:00 PM",
//     duration: "06:00",
//     stations: "ABD, BRD, BRC, SRT",
//     availableseats: 20,
//     ticketprice: 200,
//   ),
//   busdetails(
//     id: "4",
//     name: "GSRTC",
//     type: "Express",
//     departingtime: "01:00 PM",
//     reachtime: "07:00 PM",
//     duration: "06:00",
//     stations: "ABD, BRD, BRC, SRT",
//     availableseats: 15,
//     ticketprice: 125,
//   ),
//   busdetails(
//     id: "5",
//     name: "GSRTC",
//     type: "Express",
//     departingtime: "03:00 PM",
//     reachtime: "10:00 PM",
//     duration: "06:00",
//     stations: "ABD, BRD, BRC, SRT",
//     availableseats: 35,
//     ticketprice: 200,
//   ),
// ];
